service: binary-express-maciej-treder

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: production
  region: eu-central-1

package:
  exclude:
   - node_modules/**
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'

custom:
  apigwBinary:
    types:
      - 'text/html'
      - 'text/css'
      - 'image/gif'

functions:
  api:
    handler: lambda.express
    events:
      - http: ANY {proxy+}
      - http: ANY /